# frozen_string_literal: true

name              'nscd'
maintainer        'Sous Chefs'
maintainer_email  'help@sous-chefs.org'
license           'Apache-2.0'
description       'Provides resources to install, configure, manage, and clear caches for nscd'
version           '6.0.8'
source_url        'https://github.com/sous-chefs/nscd'
issues_url        'https://github.com/sous-chefs/nscd/issues'
chef_version      '>= 15.3'

supports 'almalinux', '>= 8.0'
supports 'amazon', '>= 2.0'
supports 'centos_stream', '>= 9.0'
supports 'debian', '>= 12.0'
supports 'oracle', '>= 8.0'
supports 'redhat', '>= 8.0'
supports 'rocky', '>= 8.0'
supports 'ubuntu', '>= 22.04'
