name              'nscd'
maintainer        'Sous Chefs'
maintainer_email  'help@sous-chefs.org'
license           'Apache-2.0'
description       'Installs and configures nscd'
version           '6.0.4'
source_url        'https://github.com/sous-chefs/nscd'
issues_url        'https://github.com/sous-chefs/nscd/issues'
chef_version      '>= 15.3'

supports 'amazon'
supports 'centos'
supports 'debian'
supports 'fedora'
supports 'opensuseleap'
supports 'oracle'
supports 'redhat'
supports 'scientific'
supports 'ubuntu'
